/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IAsset {
  export type AssetInfoStruct = {
    profile: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    version: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    accessControl: PromiseOrValue<string>;
    owner: PromiseOrValue<string>;
    atype: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type AssetInfoStructOutput = [
    string,
    string,
    string,
    string,
    string,
    string,
    number,
    number
  ] & {
    profile: string;
    name: string;
    version: string;
    token: string;
    accessControl: string;
    owner: string;
    atype: number;
    status: number;
  };
}

export interface IAssetInterface extends utils.Interface {
  functions: {
    "assetAccessControl()": FunctionFragment;
    "assetInfo()": FunctionFragment;
    "assetName()": FunctionFragment;
    "assetProfile()": FunctionFragment;
    "assetSafeMode()": FunctionFragment;
    "assetSetProfile(string)": FunctionFragment;
    "assetSetSafeMode(uint8)": FunctionFragment;
    "assetToken()": FunctionFragment;
    "assetType()": FunctionFragment;
    "assetVersion()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "assetAccessControl"
      | "assetAccessControl()"
      | "assetInfo"
      | "assetInfo()"
      | "assetName"
      | "assetName()"
      | "assetProfile"
      | "assetProfile()"
      | "assetSafeMode"
      | "assetSafeMode()"
      | "assetSetProfile"
      | "assetSetProfile(string)"
      | "assetSetSafeMode"
      | "assetSetSafeMode(uint8)"
      | "assetToken"
      | "assetToken()"
      | "assetType"
      | "assetType()"
      | "assetVersion"
      | "assetVersion()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assetAccessControl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetAccessControl()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assetInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetInfo()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assetName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetName()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetProfile()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetSafeMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetSafeMode()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetSetProfile",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "assetSetProfile(string)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "assetSetSafeMode",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "assetSetSafeMode(uint8)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "assetToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetToken()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assetType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetType()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assetVersion()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "assetAccessControl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetAccessControl()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetInfo()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetName()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetProfile()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSafeMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSafeMode()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSetProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSetProfile(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSetSafeMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetSetSafeMode(uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetToken()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetType()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assetVersion()",
    data: BytesLike
  ): Result;

  events: {
    "AssetProfileUpdated(address,string,string)": EventFragment;
    "AssetSafeModeUpdated(address,address,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetProfileUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AssetProfileUpdated(address,string,string)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetSafeModeUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AssetSafeModeUpdated(address,address,uint8)"
  ): EventFragment;
}

export interface AssetProfileUpdatedEventObject {
  sender: string;
  oldProfile: string;
  newProfile: string;
}
export type AssetProfileUpdatedEvent = TypedEvent<
  [string, string, string],
  AssetProfileUpdatedEventObject
>;

export type AssetProfileUpdatedEventFilter =
  TypedEventFilter<AssetProfileUpdatedEvent>;

export interface AssetSafeModeUpdatedEventObject {
  sender: string;
  assetId: string;
  status: number;
}
export type AssetSafeModeUpdatedEvent = TypedEvent<
  [string, string, number],
  AssetSafeModeUpdatedEventObject
>;

export type AssetSafeModeUpdatedEventFilter =
  TypedEventFilter<AssetSafeModeUpdatedEvent>;

export interface IAsset extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAssetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assetAccessControl(overrides?: CallOverrides): Promise<[string]>;

    "assetAccessControl()"(overrides?: CallOverrides): Promise<[string]>;

    assetInfo(
      overrides?: CallOverrides
    ): Promise<[IAsset.AssetInfoStructOutput]>;

    "assetInfo()"(
      overrides?: CallOverrides
    ): Promise<[IAsset.AssetInfoStructOutput]>;

    assetName(overrides?: CallOverrides): Promise<[string]>;

    "assetName()"(overrides?: CallOverrides): Promise<[string]>;

    assetProfile(overrides?: CallOverrides): Promise<[string]>;

    "assetProfile()"(overrides?: CallOverrides): Promise<[string]>;

    assetSafeMode(overrides?: CallOverrides): Promise<[number]>;

    "assetSafeMode()"(overrides?: CallOverrides): Promise<[number]>;

    assetSetProfile(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "assetSetProfile(string)"(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    assetSetSafeMode(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "assetSetSafeMode(uint8)"(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    assetToken(overrides?: CallOverrides): Promise<[string]>;

    "assetToken()"(overrides?: CallOverrides): Promise<[string]>;

    assetType(overrides?: CallOverrides): Promise<[number]>;

    "assetType()"(overrides?: CallOverrides): Promise<[number]>;

    assetVersion(overrides?: CallOverrides): Promise<[string]>;

    "assetVersion()"(overrides?: CallOverrides): Promise<[string]>;
  };

  assetAccessControl(overrides?: CallOverrides): Promise<string>;

  "assetAccessControl()"(overrides?: CallOverrides): Promise<string>;

  assetInfo(overrides?: CallOverrides): Promise<IAsset.AssetInfoStructOutput>;

  "assetInfo()"(
    overrides?: CallOverrides
  ): Promise<IAsset.AssetInfoStructOutput>;

  assetName(overrides?: CallOverrides): Promise<string>;

  "assetName()"(overrides?: CallOverrides): Promise<string>;

  assetProfile(overrides?: CallOverrides): Promise<string>;

  "assetProfile()"(overrides?: CallOverrides): Promise<string>;

  assetSafeMode(overrides?: CallOverrides): Promise<number>;

  "assetSafeMode()"(overrides?: CallOverrides): Promise<number>;

  assetSetProfile(
    profile: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "assetSetProfile(string)"(
    profile: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  assetSetSafeMode(
    status: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "assetSetSafeMode(uint8)"(
    status: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  assetToken(overrides?: CallOverrides): Promise<string>;

  "assetToken()"(overrides?: CallOverrides): Promise<string>;

  assetType(overrides?: CallOverrides): Promise<number>;

  "assetType()"(overrides?: CallOverrides): Promise<number>;

  assetVersion(overrides?: CallOverrides): Promise<string>;

  "assetVersion()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    assetAccessControl(overrides?: CallOverrides): Promise<string>;

    "assetAccessControl()"(overrides?: CallOverrides): Promise<string>;

    assetInfo(overrides?: CallOverrides): Promise<IAsset.AssetInfoStructOutput>;

    "assetInfo()"(
      overrides?: CallOverrides
    ): Promise<IAsset.AssetInfoStructOutput>;

    assetName(overrides?: CallOverrides): Promise<string>;

    "assetName()"(overrides?: CallOverrides): Promise<string>;

    assetProfile(overrides?: CallOverrides): Promise<string>;

    "assetProfile()"(overrides?: CallOverrides): Promise<string>;

    assetSafeMode(overrides?: CallOverrides): Promise<number>;

    "assetSafeMode()"(overrides?: CallOverrides): Promise<number>;

    assetSetProfile(
      profile: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "assetSetProfile(string)"(
      profile: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    assetSetSafeMode(
      status: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "assetSetSafeMode(uint8)"(
      status: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    assetToken(overrides?: CallOverrides): Promise<string>;

    "assetToken()"(overrides?: CallOverrides): Promise<string>;

    assetType(overrides?: CallOverrides): Promise<number>;

    "assetType()"(overrides?: CallOverrides): Promise<number>;

    assetVersion(overrides?: CallOverrides): Promise<string>;

    "assetVersion()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AssetProfileUpdated(address,string,string)"(
      sender?: PromiseOrValue<string> | null,
      oldProfile?: PromiseOrValue<string> | null,
      newProfile?: PromiseOrValue<string> | null
    ): AssetProfileUpdatedEventFilter;
    AssetProfileUpdated(
      sender?: PromiseOrValue<string> | null,
      oldProfile?: PromiseOrValue<string> | null,
      newProfile?: PromiseOrValue<string> | null
    ): AssetProfileUpdatedEventFilter;

    "AssetSafeModeUpdated(address,address,uint8)"(
      sender?: PromiseOrValue<string> | null,
      assetId?: PromiseOrValue<string> | null,
      status?: null
    ): AssetSafeModeUpdatedEventFilter;
    AssetSafeModeUpdated(
      sender?: PromiseOrValue<string> | null,
      assetId?: PromiseOrValue<string> | null,
      status?: null
    ): AssetSafeModeUpdatedEventFilter;
  };

  estimateGas: {
    assetAccessControl(overrides?: CallOverrides): Promise<BigNumber>;

    "assetAccessControl()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetInfo(overrides?: CallOverrides): Promise<BigNumber>;

    "assetInfo()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetName(overrides?: CallOverrides): Promise<BigNumber>;

    "assetName()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetProfile(overrides?: CallOverrides): Promise<BigNumber>;

    "assetProfile()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetSafeMode(overrides?: CallOverrides): Promise<BigNumber>;

    "assetSafeMode()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetSetProfile(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "assetSetProfile(string)"(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    assetSetSafeMode(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "assetSetSafeMode(uint8)"(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    assetToken(overrides?: CallOverrides): Promise<BigNumber>;

    "assetToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetType(overrides?: CallOverrides): Promise<BigNumber>;

    "assetType()"(overrides?: CallOverrides): Promise<BigNumber>;

    assetVersion(overrides?: CallOverrides): Promise<BigNumber>;

    "assetVersion()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    assetAccessControl(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "assetAccessControl()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    assetInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetInfo()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetProfile(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetProfile()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetSafeMode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetSafeMode()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetSetProfile(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "assetSetProfile(string)"(
      profile: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    assetSetSafeMode(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "assetSetSafeMode(uint8)"(
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    assetToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetType()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    assetVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "assetVersion()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
