/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Asset } from "./ERC20Asset";
export type { ERC20AssetExtra } from "./ERC20AssetExtra";
export type { ERC20AssetLockable } from "./ERC20AssetLockable";
export type { IAsset } from "./IAsset";
export type { IERC20Asset } from "./IERC20Asset";
export type { IERC20AssetExtra } from "./IERC20AssetExtra";
export type { IERC20AssetLockable } from "./IERC20AssetLockable";
