/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20AssetFundingTeamTestSol from "./ERC20AssetFundingTeamTest.sol";
export * as erc20AssetPublicSalesTestSol from "./ERC20AssetPublicSalesTest.sol";
export * as erc20TokenTestSol from "./ERC20TokenTest.sol";
export { IACLTest__factory } from "./IACLTest__factory";
