/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IProfileACLInterface extends utils.Interface {
  functions: {
    "profileHasAccess(bytes32,bytes32)": FunctionFragment;
    "profileHasAccountAccess(bytes32,address,bytes4,address)": FunctionFragment;
    "profileHasCSAccess(bytes32,address,bytes4)": FunctionFragment;
    "profileHasMemberAccess(bytes32,bytes32,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "profileHasAccess"
      | "profileHasAccountAccess"
      | "profileHasCSAccess"
      | "profileHasMemberAccess"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "profileHasAccess",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "profileHasAccountAccess",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "profileHasCSAccess",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "profileHasMemberAccess",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "profileHasAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileHasAccountAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileHasCSAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileHasMemberAccess",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IProfileACL extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IProfileACLInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    profileHasAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    profileHasAccountAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      accountId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    profileHasCSAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    profileHasMemberAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      memberId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  profileHasAccess(
    profileId: PromiseOrValue<BytesLike>,
    functionId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  profileHasAccountAccess(
    profileId: PromiseOrValue<BytesLike>,
    contractId: PromiseOrValue<string>,
    selector: PromiseOrValue<BytesLike>,
    accountId: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  profileHasCSAccess(
    profileId: PromiseOrValue<BytesLike>,
    contractId: PromiseOrValue<string>,
    selector: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  profileHasMemberAccess(
    profileId: PromiseOrValue<BytesLike>,
    functionId: PromiseOrValue<BytesLike>,
    memberId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    profileHasAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    profileHasAccountAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      accountId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    profileHasCSAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    profileHasMemberAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      memberId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    profileHasAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    profileHasAccountAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      accountId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    profileHasCSAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    profileHasMemberAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      memberId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    profileHasAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    profileHasAccountAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      accountId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    profileHasCSAccess(
      profileId: PromiseOrValue<BytesLike>,
      contractId: PromiseOrValue<string>,
      selector: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    profileHasMemberAccess(
      profileId: PromiseOrValue<BytesLike>,
      functionId: PromiseOrValue<BytesLike>,
      memberId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
