/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export declare namespace IERC20Taxable {
  export type TaxWhitelistUpdateRequestStruct = {
    account: PromiseOrValue<string>;
    isDeleted: PromiseOrValue<boolean>;
  };

  export type TaxWhitelistUpdateRequestStructOutput = [string, boolean] & {
    account: string;
    isDeleted: boolean;
  };
}

export interface IERC20TaxableInterface extends utils.Interface {
  functions: {
    "taxRate()": FunctionFragment;
    "taxTreasury()": FunctionFragment;
    "taxUpdateRate(uint256)": FunctionFragment;
    "taxUpdateTreasury(address)": FunctionFragment;
    "taxUpdateWhitelist((address,bool)[])": FunctionFragment;
    "taxWhitelist(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "taxRate"
      | "taxTreasury"
      | "taxUpdateRate"
      | "taxUpdateTreasury"
      | "taxUpdateWhitelist"
      | "taxWhitelist"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "taxRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "taxTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taxUpdateRate",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "taxUpdateTreasury",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "taxUpdateWhitelist",
    values: [IERC20Taxable.TaxWhitelistUpdateRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "taxWhitelist",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "taxRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taxTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxUpdateRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxUpdateTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxUpdateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxWhitelist",
    data: BytesLike
  ): Result;

  events: {
    "TaxRateUpdated(address,uint256)": EventFragment;
    "TaxTreasuryUpdated(address,address)": EventFragment;
    "TaxWhitelistUpdated(address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TaxRateUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TaxTreasuryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TaxWhitelistUpdated"): EventFragment;
}

export interface TaxRateUpdatedEventObject {
  sender: string;
  rate: BigNumber;
}
export type TaxRateUpdatedEvent = TypedEvent<
  [string, BigNumber],
  TaxRateUpdatedEventObject
>;

export type TaxRateUpdatedEventFilter = TypedEventFilter<TaxRateUpdatedEvent>;

export interface TaxTreasuryUpdatedEventObject {
  sender: string;
  account: string;
}
export type TaxTreasuryUpdatedEvent = TypedEvent<
  [string, string],
  TaxTreasuryUpdatedEventObject
>;

export type TaxTreasuryUpdatedEventFilter =
  TypedEventFilter<TaxTreasuryUpdatedEvent>;

export interface TaxWhitelistUpdatedEventObject {
  sender: string;
  account: string;
  isDeleted: boolean;
}
export type TaxWhitelistUpdatedEvent = TypedEvent<
  [string, string, boolean],
  TaxWhitelistUpdatedEventObject
>;

export type TaxWhitelistUpdatedEventFilter =
  TypedEventFilter<TaxWhitelistUpdatedEvent>;

export interface IERC20Taxable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC20TaxableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    taxRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    taxTreasury(overrides?: CallOverrides): Promise<[string]>;

    taxUpdateRate(
      taxRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    taxUpdateTreasury(
      treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    taxUpdateWhitelist(
      request: IERC20Taxable.TaxWhitelistUpdateRequestStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    taxWhitelist(
      offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;
  };

  taxRate(overrides?: CallOverrides): Promise<BigNumber>;

  taxTreasury(overrides?: CallOverrides): Promise<string>;

  taxUpdateRate(
    taxRate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  taxUpdateTreasury(
    treasury: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  taxUpdateWhitelist(
    request: IERC20Taxable.TaxWhitelistUpdateRequestStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  taxWhitelist(
    offset: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  callStatic: {
    taxRate(overrides?: CallOverrides): Promise<BigNumber>;

    taxTreasury(overrides?: CallOverrides): Promise<string>;

    taxUpdateRate(
      taxRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    taxUpdateTreasury(
      treasury: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    taxUpdateWhitelist(
      request: IERC20Taxable.TaxWhitelistUpdateRequestStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    taxWhitelist(
      offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;
  };

  filters: {
    "TaxRateUpdated(address,uint256)"(
      sender?: PromiseOrValue<string> | null,
      rate?: null
    ): TaxRateUpdatedEventFilter;
    TaxRateUpdated(
      sender?: PromiseOrValue<string> | null,
      rate?: null
    ): TaxRateUpdatedEventFilter;

    "TaxTreasuryUpdated(address,address)"(
      sender?: PromiseOrValue<string> | null,
      account?: null
    ): TaxTreasuryUpdatedEventFilter;
    TaxTreasuryUpdated(
      sender?: PromiseOrValue<string> | null,
      account?: null
    ): TaxTreasuryUpdatedEventFilter;

    "TaxWhitelistUpdated(address,address,bool)"(
      sender?: PromiseOrValue<string> | null,
      account?: PromiseOrValue<string> | null,
      isDeleted?: null
    ): TaxWhitelistUpdatedEventFilter;
    TaxWhitelistUpdated(
      sender?: PromiseOrValue<string> | null,
      account?: PromiseOrValue<string> | null,
      isDeleted?: null
    ): TaxWhitelistUpdatedEventFilter;
  };

  estimateGas: {
    taxRate(overrides?: CallOverrides): Promise<BigNumber>;

    taxTreasury(overrides?: CallOverrides): Promise<BigNumber>;

    taxUpdateRate(
      taxRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    taxUpdateTreasury(
      treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    taxUpdateWhitelist(
      request: IERC20Taxable.TaxWhitelistUpdateRequestStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    taxWhitelist(
      offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    taxRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    taxTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    taxUpdateRate(
      taxRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    taxUpdateTreasury(
      treasury: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    taxUpdateWhitelist(
      request: IERC20Taxable.TaxWhitelistUpdateRequestStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    taxWhitelist(
      offset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
