/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Burnable__factory } from "./ERC20Burnable__factory";
export { ERC20Extra__factory } from "./ERC20Extra__factory";
export { ERC20Lockable__factory } from "./ERC20Lockable__factory";
export { ERC20Mintable__factory } from "./ERC20Mintable__factory";
export { ERC20Pausable__factory } from "./ERC20Pausable__factory";
export { ERC20Permitable__factory } from "./ERC20Permitable__factory";
export { ERC20Taxable__factory } from "./ERC20Taxable__factory";
export { IERC20Burnable__factory } from "./IERC20Burnable__factory";
export { IERC20Extra__factory } from "./IERC20Extra__factory";
export { IERC20Lockable__factory } from "./IERC20Lockable__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { IERC20Pausable__factory } from "./IERC20Pausable__factory";
export { IERC20Permitable__factory } from "./IERC20Permitable__factory";
export { IERC20Taxable__factory } from "./IERC20Taxable__factory";
