/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20AssetFundingTeamTestSol from "./ERC20AssetFundingTeamTest.sol";
export type { erc20AssetFundingTeamTestSol };
import type * as erc20AssetPublicSalesTestSol from "./ERC20AssetPublicSalesTest.sol";
export type { erc20AssetPublicSalesTestSol };
import type * as erc20TokenTestSol from "./ERC20TokenTest.sol";
export type { erc20TokenTestSol };
export type { IACLTest } from "./IACLTest";
